# Generated by Django 4.1 on 2022-09-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cml_number', models.IntegerField()),
                ('cml_description', models.TextField()),
                ('actual_outside_diameter', models.FloatField()),
                ('design_thickness', models.IntegerField()),
                ('structural_thickness', models.IntegerField()),
                ('require_thickness', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cml',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('from_start', models.TextField()),
                ('to', models.TextField()),
                ('drawing_number', models.TextField()),
                ('service', models.TextField()),
                ('material', models.TextField()),
                ('inservice_date', models.DateField()),
                ('pipe_size', models.IntegerField()),
                ('original_thickness', models.FloatField()),
                ('stress', models.IntegerField()),
                ('joint_efficiency', models.IntegerField()),
                ('ca', models.IntegerField()),
                ('design_life', models.IntegerField()),
                ('design_pressure', models.IntegerField()),
                ('operating_pressure', models.IntegerField()),
                ('design_temperature', models.IntegerField()),
                ('operating_temperature', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Info',
            },
        ),
        migrations.CreateModel(
            name='Test_Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_number', models.IntegerField()),
                ('tp_description', models.IntegerField()),
                ('note', models.TextField()),
                ('cml_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Pipingsite.cml', verbose_name='Cml')),
            ],
            options={
                'verbose_name_plural': 'Test_Point',
            },
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('actual_thickness', models.IntegerField()),
                ('tp_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Pipingsite.test_point', verbose_name='Test_Point')),
            ],
        ),
        migrations.AddField(
            model_name='cml',
            name='line_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Pipingsite.info', verbose_name='Info'),
        ),
    ]
