# Generated by Django 4.1 on 2022-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipingsite', '0002_alter_cml_actual_outside_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cml',
            name='actual_outside_diameter',
            field=models.FloatField(),
        ),
    ]
