# Generated by Django 4.1 on 2022-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipingsite', '0005_alter_cml_design_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cml',
            name='structural_thickness',
            field=models.FloatField(),
        ),
    ]
