# Generated by Django 4.1 on 2022-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipingsite', '0006_alter_cml_structural_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cml',
            name='require_thickness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cml',
            name='structural_thickness',
            field=models.FloatField(default=0.0),
        ),
    ]
