# Generated by Django 4.1 on 2022-09-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipingsite', '0008_alter_test_point_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thickness',
            name='actual_thickness',
            field=models.FloatField(),
        ),
    ]
